-- HAVING

SELECT * FROM users HAVING age > 20;
SELECT * FROM users HAVING age > 19;
SELECT * FROM users HAVING age > 14;
SELECT COUNT(age) FROM users HAVING COUNT(age) > 0;
SELECT COUNT(age) FROM users HAVING COUNT(age) > 3;
SELECT COUNT(age) FROM users HAVING COUNT(age) > 4;